### PR TITLE
Add marker anchor support

### PR DESCRIPTION
**Pull request by milare**
Implements #26

### CODE REVIEW

**Comment by johnpryan** [comment]
Thanks for the contribution!

Just a heads up, we are going to also make the offset calculation automatic:

```
      new Marker(
          width: 80.0,
          height: 80.0,
          point: new LatLng(53.3498, -6.2603),
          builder: (ctx) => new Container(
                child: new FlutterLogo(
                  colors: Colors.green,
                ),
              ),
          anchor: MarkerAnchor.center),
```

so that users won't need to think about dividing 80.0 / 2 and setting the anchor point manually.

Let me know if that doesn't work for your use case or you have any questions!

**Comment by johnpryan** [comment]
New API: 48a5a3e06204c8c480e097da0c6ce7cf69070222

**Comment by milare** [comment]
That's even better, thanks!

**Comment by Leffe108** [comment]
It may help other people to know that this is how you specify anchorPos to Marker constructor.

```dart
Marker(
  anchorPos: AnchorPos.align(AnchorAlign.bottom),
  ...
```

**Pull request merged**
